# Generated by Django 4.2.15 on 2024-09-10 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="OAuthToken",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "access_token",
                    models.CharField(max_length=255, verbose_name="Токен доступа"),
                ),
                ("expires_at", models.DateTimeField(verbose_name="Истекает в")),
            ],
            options={
                "verbose_name": "Токен доступа",
                "verbose_name_plural": "Токены доступа",
                "db_table": "oauth_token",
            },
        ),
    ]
