# Generated by Django 4.2.15 on 2024-09-09 17:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("oauth", "0001_initial"),
        ("projects", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="oauthtoken",
            name="project",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="oauth_tokens",
                to="projects.project",
                verbose_name="Айди проекта",
            ),
        ),
        migrations.AddField(
            model_name="oauthtoken",
            name="system",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="oauth_tokens",
                to="projects.system",
                verbose_name="Айди системы",
            ),
        ),
    ]
