# Generated by Django 4.2.15 on 2024-09-06 16:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("oauth", "0002_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="oauthtoken",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="oauth_tokens",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Айди пользователя",
            ),
        ),
    ]
